#!/usr/bin/env node
/**
 * Fetches the two asset groups the HTML doesn't reference directly:
 *
 *  1. Google "Inter" (300..700) — the live page loads this at runtime via
 *     `WebFont.load({google:{families:["Inter:300,400,500,600,700"]}})`, so it
 *     never appears as a <link> in the HTML. We self-host it and emit a local
 *     @font-face stylesheet so the replica makes zero remote font requests.
 *
 *  2. The Rive WebGL2 runtime wasm. The live site loads
 *     @rive-app/webgl2@2.35.0 (verified: it fetches
 *     unpkg.com/@rive-app/webgl2@2.35.0/rive.wasm). The .riv used by the hero
 *     chart does NOT render on the plain @rive-app/canvas renderer, so the
 *     webgl2 build is mandatory, not interchangeable.
 *
 * Note: fonts.googleapis.com/css2?family=IBM+Plex+Sans is deliberately NOT
 * fetched — that request is injected by Amplitude's analytics bundle, not by
 * the page design, and no page element uses IBM Plex Sans.
 */
import { mkdir, readFile, writeFile, stat } from 'node:fs/promises';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const FONT_DIR = path.join(ROOT, 'public', 'assets', 'fonts');
const RIVE_DIR = path.join(ROOT, 'public', 'assets', 'rive');
const STYLE_DIR = path.join(ROOT, 'app', 'styles');

// A modern UA is required or the css2 endpoint serves legacy ttf instead of woff2.
const UA =
  'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 ' +
  '(KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36';

const RIVE_VERSION = '2.35.0';
const RIVE_WASM_URL = `https://unpkg.com/@rive-app/webgl2@${RIVE_VERSION}/rive.wasm`;
const INTER_CSS_URL =
  'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&display=swap';

async function exists(p) {
  try {
    await stat(p);
    return true;
  } catch {
    return false;
  }
}

async function fetchBuf(url) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${url}`);
  return Buffer.from(await res.arrayBuffer());
}

async function fetchInter() {
  await mkdir(FONT_DIR, { recursive: true });
  await mkdir(STYLE_DIR, { recursive: true });

  const css = (await fetchBuf(INTER_CSS_URL)).toString('utf8');
  const urls = [...css.matchAll(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/g)].map((m) => m[1]);
  const unique = [...new Set(urls)];
  console.log(`inter: ${unique.length} woff2 files referenced`);

  let localCss = css;
  let downloaded = 0;
  for (const url of unique) {
    // gstatic Inter filenames are opaque hashes; derive a readable, stable name
    // from the subset comment order instead by just reusing the basename.
    const base = path.basename(url.split('?')[0]);
    const name = `inter-${base}`;
    const dest = path.join(FONT_DIR, name);
    if (!(await exists(dest))) {
      await writeFile(dest, await fetchBuf(url));
      downloaded += 1;
    }
    localCss = localCss.split(url).join(`/assets/fonts/${name}`);
  }

  const header =
    '/* Generated by scripts/fetch-extras.mjs — do not edit by hand.\n' +
    ' * Self-hosted mirror of the Google "Inter" family that coframe.com loads\n' +
    ' * at runtime through WebFont.load. Regenerate with `npm run extras`.\n' +
    ' */\n';
  await writeFile(path.join(STYLE_DIR, 'inter.css'), header + localCss);

  const faces = (localCss.match(/@font-face/g) ?? []).length;
  console.log(`inter: ${downloaded} newly downloaded, ${faces} @font-face rules -> app/styles/inter.css`);
  return { files: unique.length, faces };
}

async function fetchRiveWasm() {
  await mkdir(RIVE_DIR, { recursive: true });
  const dest = path.join(RIVE_DIR, 'rive-webgl2.wasm');
  if (await exists(dest)) {
    const buf = await readFile(dest);
    console.log(`rive wasm: cached (${buf.length}b)`);
    return { bytes: buf.length, cached: true };
  }
  const buf = await fetchBuf(RIVE_WASM_URL);
  await writeFile(dest, buf);
  console.log(`rive wasm: ${buf.length}b -> public/assets/rive/rive-webgl2.wasm`);
  return { bytes: buf.length };
}

async function main() {
  const inter = await fetchInter();
  const rive = await fetchRiveWasm();
  console.log('\n--- extras summary ---');
  console.log(`Inter woff2 files : ${inter.files}`);
  console.log(`Inter @font-face  : ${inter.faces}`);
  console.log(`Rive webgl2 wasm  : ${rive.bytes} bytes (v${RIVE_VERSION})`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
