// Builds the replica's stylesheets from the scraped source, preserving the
// original document order:
//
//   app/styles/fonts.css     self-hosted Inter faces (page used WebFont.load)
//   app/styles/webflow.css   the 217 KB Webflow shared stylesheet
//   app/styles/vendor.css    fancybox + swiper bundles
//   app/styles/embedded.css  all 21 inline <style> blocks, in document order
//
// Every url(...) is rewritten to a self-hosted /assets/... path.
import { readFile, writeFile, mkdir, readdir } from 'node:fs/promises';
import path from 'node:path';
import { loadAssetMap, rewriteCssUrls } from './lib/rewrite.mjs';

const ROOT = path.resolve(import.meta.dirname, '..');
const RAW = path.join(ROOT, 'scrape', 'raw');
const OUT = path.join(ROOT, 'app', 'styles');

const map = await loadAssetMap();
await mkdir(OUT, { recursive: true });

const banner = (what) =>
  `/* Generated by scripts/gen-css.mjs from the live coframe.com source.\n   Source: ${what}\n   Do not edit by hand - re-run \`npm run gen:css\`. */\n\n`;

// --- 1. Fonts -------------------------------------------------------------
const googleCss = await readFile(path.join(ROOT, 'scrape', 'google-fonts.css'), 'utf8');
await writeFile(
  path.join(OUT, 'fonts.css'),
  banner('fonts.googleapis.com/css2?family=Inter:wght@300..700 (self-hosted)') +
    rewriteCssUrls(googleCss, map),
);

// --- 2. Webflow shared stylesheet ----------------------------------------
const cssDir = path.join(RAW, 'css');
const cssFiles = (await readdir(cssDir)).filter((f) => f.endsWith('.css')).sort();
const webflowFile = cssFiles.find((f) => f.includes('webflow.shared'));
const webflowCss = await readFile(path.join(cssDir, webflowFile), 'utf8');
await writeFile(
  path.join(OUT, 'webflow.css'),
  banner(webflowFile) + rewriteCssUrls(webflowCss, map),
);

// --- 3. Vendor (fancybox, swiper) ----------------------------------------
const vendorParts = [];
for (const f of cssFiles) {
  if (f === webflowFile) continue;
  const css = await readFile(path.join(cssDir, f), 'utf8');
  vendorParts.push(`/* ===== ${f} ===== */\n${rewriteCssUrls(css, map)}`);
}
await writeFile(
  path.join(OUT, 'vendor.css'),
  banner(cssFiles.filter((f) => f !== webflowFile).join(', ')) + vendorParts.join('\n\n'),
);

// --- 4. Inline <style> blocks, in document order -------------------------
const inlineIndex = JSON.parse(await readFile(path.join(RAW, 'inline-index.json'), 'utf8'));
const styles = inlineIndex.filter((e) => e.kind === 'style').sort((a, b) => a.offset - b.offset);
const embeddedParts = [];
for (const s of styles) {
  const css = await readFile(path.join(RAW, path.basename(path.dirname(s.file)), path.basename(s.file)), 'utf8');
  embeddedParts.push(`/* ===== ${path.basename(s.file)} (source offset ${s.offset}) ===== */\n${rewriteCssUrls(css, map).trim()}`);
}
await writeFile(
  path.join(OUT, 'embedded.css'),
  banner(`${styles.length} inline <style> blocks from index.html`) + embeddedParts.join('\n\n'),
);

const sizes = {};
for (const f of ['fonts.css', 'webflow.css', 'vendor.css', 'embedded.css']) {
  sizes[f] = (await readFile(path.join(OUT, f), 'utf8')).length;
}
console.log('Wrote app/styles:', sizes);
console.log(`embedded.css merges ${styles.length} inline style blocks`);
